version: '3.8'

services:
  application:
    container_name: edf
    image: 'edf'
    build:
      context: .
    env_file: .env
    volumes:
      - files:/home/edf/files
    ports:
      - "8080:8080"